### ISSUE TITLE
Align metadata with some other standards

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/ndx-microscopy#3]
@alessandratrapani 

Two other standards worth checking out

https://doryworkspace.org/metadata

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/10-microscopy.html

**Comment by ehennestad** [comment]
I think the OME-TIFF specification should be added to this list
https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#OME_OME_BinaryOnly_MetadataFile

A subset of these are described here:
https://www.mbfbioscience.com/help/microfileplus_vault/microfileplus_2020/Content/MetadataGlossary.htm
