### ISSUE TITLE
Light Beads Microscopy

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/ndx-microscopy#8]
Just noticed this: https://github.com/dandi/helpdesk/discussions/125

What is light beads microscopy, and does this extension account for it?

@alessandratrapani

**Comment by alessandratrapani** [comment]
It's a technique where basically the light beam is multiplexed to simultaneously acquire planes at different depths. 
So far, the "illumination_type" property of the `Microscope` can differentiate between the different type of illumination technique (e.g. confocatl, light sheet, light beads). And I guess in this case the `plane_acquisitio_rate` would be equal to the `rate` of the `VolumetricMicroscopySeries`

**Comment by CodyCBakerPhD** [comment]
Fantastic, thanks for checking!
